### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by yin00030** [MTM6330-F18/Final-Avatar#3]
- Interview 
- Interview scripts 
- Interview audio

( uploads to google drive. Folder Name: Interview)

**Comment by mokh0009** [comment]
[Audio.zip](https://github.com/MTM6330-F18/Final-Avatar/files/2574542/Audio.zip)
[Scripts.zip](https://github.com/MTM6330-F18/Final-Avatar/files/2574543/Scripts.zip)
