### ISSUE TITLE
Info Collection: course page & 4 professor sub-pages 

### ISSUE THREAD

**Issue by yin00030** [MTM6330-F18/Final-Avatar#4]
Collect Infomation

-a detailed page describing each course, the topics covered, the professor, and the grading
-a detailed page describing each professor, their contact information and the courses taught

Due Date: Nov 13

where can find "grading"? go each course in bright space-content-Official Course Outline
PDF document (last file)- find Grade Scheme(look at screen below) 
 
https://drive.google.com/file/d/1CyJZsBYIW-OocOIE3gdiyHtF2Ks9zW5Q/view?usp=sharing

**Comment by yaningxue** [comment]
Fixes #4

**Comment by yaningxue** [comment]
Completed this issue, and already upload the file to google drive. link is https://drive.google.com/file/d/17kwUG1NchRZdnSB42RC3wL0vRdQN3T7O/view?usp=sharing

But I don't know how to close it. I think maybe only team leader can close the issues.
